### ISSUE TITLE
Test Advert Queries

### ISSUE THREAD

**Issue by iWareDesigns** [mobfox/MobFox-Android-SDK#56]
Hi,

We are using AdMob as our mediation platform and have recently added MobFox.  We are running test adverts and have the following two queries.

1. The banner advert is wider than the screen?  We are using AdMob's SMART_BANNER.
2. The interstitial advert does not fill the screen?  Is this correct?  The Asus Nexus device we are using has a 7" screen, the interstitial advert looks like a phone size,

I have attached a screen  grab of the banner advert and interstitial advert.

Regards,

iWare Designs Ltd.
![android_asus_nexus_tablet_testbannerad](https://cloud.githubusercontent.com/assets/28161411/25695814/7fc5bd1e-30ac-11e7-8b8a-b5c124369033.png)
![android_asus_nexus_interstitialad](https://cloud.githubusercontent.com/assets/28161411/25695824/8696002c-30ac-11e7-980c-e77e65bcca8b.png)

**Comment by asafgaber** [comment]
Hi,
regarding your issues
1. are you displaying the smart banner on a tablet? if so that will explain the mistake in size.
we are implementing a fix for tablet size banners.
2. our interstitial is also not perfectly adapted to tablet size. we will fix that.

I believe we will fix these two issue by early next week.
Regards

**Comment by iWareDesigns** [comment]
Hi,

Yes, the smart banner is being used on a tablet.

Is it just the test banners that do not work correctly?  Or is the problem with live adverts also?

Regards,

iWare Designs Ltd.

**Comment by nabriski** [comment]
Hi,
We've just released a fix for the first issue in 3.2.5e.
The second issue fix  - a bigger ad for interstitial on tablet, will be released in a few days.

**Comment by iWareDesigns** [comment]
Hi,

We have just added in 3.2.5e and the latest AdMob adapter and the banners seem to be no different.  We have cleaned the project twice, performed completed rebuilds and downloaded the SDK and Adapter more than once from Github, but we are still seeing the smart banner being clipped.

![screenshot_20170510-154858](https://cloud.githubusercontent.com/assets/28161411/25905291/85645d6a-3599-11e7-8881-83eed066914d.png)

**Comment by nabriski** [comment]
Very strange, I saw it working on our tablet myself.
Can you please send us a link to your apk? (you can send it to my email - itamar.n@matomy.com)

Thanks

**Comment by nabriski** [comment]
Hi,
Please try these:
http://static.starbolt.io/MobFox-Android-SDK-Core-3.2.5f.jar
http://static.starbolt.io/MobFox-Android-AdMob-Adapter-2017-05-11.jar

They contain fixes for both 1 & 2.

**Comment by iWareDesigns** [comment]
Hi,
Thanks for the update, I have attached a screenshot from our Nexus 7 2nd generation device.

![android_nexus7_smartbanner](https://cloud.githubusercontent.com/assets/28161411/25951079/8920eac0-3654-11e7-81aa-7ca931b6523a.png)

**Comment by nabriski** [comment]
Is this a 1920 x 1200 device?

**Comment by iWareDesigns** [comment]
Hi,

Yes, it is a 1920 x 1200 device.

Regards,

iWare Designs.

**Comment by iWareDesigns** [comment]
Hi,

I have just been playing around with different formats on Android and that banner adverts looks like it is a 50 dp high advert, should it be 90 dp and fill in to the bottom of the screen?

Regards,

iWare Designs Ltd.

**Comment by nabriski** [comment]
How did you define it in AdMob? we translate their sizes to ours.

**Comment by iWareDesigns** [comment]
Hi,

We use "com.google.android.gms.ads.AdSize.SMART_BANNER", code fragment below:

//	Creates the banner adView
this.bannerView = new com.google.android.gms.ads.AdView(Prophet.appActivity);
this.bannerView.setAdUnitId(Prophet.bannerAdMediationId);
this.bannerView.setAdSize(com.google.android.gms.ads.AdSize.SMART_BANNER);

Regards,

iWare Designs.

**Comment by iWareDesigns** [comment]
Hi,

We have just been reviewing the Android Smart Banners and we still think there is a problem with sizing.  This is on a phone.

I have 3 images below:

MobFox Banner which should display at 320 x 50 DP.

![swift2plus_banner](https://cloud.githubusercontent.com/assets/28161411/25990948/8008924e-36f9-11e7-9246-e64297f8e8df.png)

MobFox Smart Banner which should display at full screen width x 32 DP, but is displaying at full screen width x 50 DP.

![swift2plus_smart_smartbanner](https://cloud.githubusercontent.com/assets/28161411/25990995/a9f72c32-36f9-11e7-8dec-f814d1510b9f.png)

AdMob Smart Banner which is displayed at full screen width x 32 DP.

![swift2plus_admob_smartbanner](https://cloud.githubusercontent.com/assets/28161411/25991015/bd0ca248-36f9-11e7-9afb-cc9567fed680.png)

The phone we are using is less than 400 DP which according to AdMob's Smart Banner specification should be 32 DP high.

https://firebase.google.com/docs/admob/android/banner

Regards,

iWare Designs.

**Comment by nabriski** [comment]
Hi,

I need to check with our demand team if we have X*32 banners. If not, we can just return a "no fill" in this case so you can go to your next demand source.

**Comment by iWareDesigns** [comment]
Hi,

Okay that sounds good.

I am currently testing landscape smart banners on an Apple iPhone 6+ and am not seeing any MobFox test adverts.  Would I be right in saying that landscape smart banner requests on phones are returning a "no fill"?  

Regards,

iWare Designs.

**Comment by nabriski** [comment]
Most probably, I'll have a definitive answer on Sunday.

Regards,
Itamar

**Comment by iWareDesigns** [comment]
Hi,

I have just being trying out different banner types in our games and have been testing the IAB_FULL_BANNER 468 x 60.  The MobFox SDK seems to be showing  a SMART_BANNER.

MobFox advert when using IAB_FULL_BANNER through AdMob mediation.

![android_iab_fullbanner_mobfox](https://cloud.githubusercontent.com/assets/28161411/26025231/efc70bba-37da-11e7-8b2c-24f17f9e8d8b.png)

AdMob advert when using IAB_FULL_BANNER through AdMob mediation

![android_iab_fullbanner_admob](https://cloud.githubusercontent.com/assets/28161411/26025232/fb5cb632-37da-11e7-94db-f0290a8dcf9b.png)

The MobFox banner seems to be the incorrect width and height.  And the banner extends to the edges of the display with a black border.

Following on from an earlier post, the screen shot below shows a SMART_BANNER, which also looks to be incorrect as there is a gap between the bottom of the advert and the bottom of the screen.

![nexus7_smartbanner](https://cloud.githubusercontent.com/assets/28161411/26025259/6d98d6ea-37db-11e7-8984-ed04231c7973.png)

I have also just found this article on the MobFox website https://docs.mobfox.com/docs/banners-1 which shows the banner and interstitial sizes.  Are these the only sizes supported through the MobFox network?

Regards,

iWare Designs.

**Comment by nabriski** [comment]
Hi,

I've discussed this Eli and will answer it over mail.

Regards,
Itamar

**Comment by iWareDesigns** [comment]
Hi,

Following up on our conversations in May, would it be possible to remove the black bar behind your adverts when using AdMob SMART_BANNERS and AdMob Mediation?

I understand that we will receive a 320 x 50 banner advert, but I think visually it would better without the addition of the black in fill bar.  I know that the AdMob specification for a SMART_BANNER is full width of the screen, however a floating 320 x 50 banner with no in fill would be ideal.

![smartbanner](https://user-images.githubusercontent.com/28161411/28222551-e99845ae-68bf-11e7-9d62-99cb2ff934b3.png)

Regards,

iWare Designs.

**Comment by nabriski** [comment]
Hi,
I'll discuss it with Android dev but I don't see a problem adding this setting quickly.
We'll update this issue with our progress.

**Comment by iWareDesigns** [comment]
Hi Nabriski,

Thanks for the quick response.  This morning I tried to use the standard BANNER ad size through the AdMob mediation and got the following advert displayed.  I believe that the standard BANNER should be 320 x 50 with no full screen width in fill.

![screenshot_20170715-114041](https://user-images.githubusercontent.com/28161411/28238764-b6fad560-6952-11e7-9826-4543f3bf8314.png)

**Comment by nabriski** [comment]
Very strange, we'll try to reproduce this. Can you please share with us your ad placement code?
Thanks

**Comment by iWareDesigns** [comment]
Hi,

Here is out create banner function / method.

	private void createBannerView()
	{
		
		float MaxAdvertHeight;
		RelativeLayout.LayoutParams params;
		
		//	Creates banner advert
		if (this.bannerView == null)
		{

			//	Creates the banner adView
			this.bannerView = new com.google.android.gms.ads.AdView(Prophet.appActivity);
			this.bannerView.setAdUnitId(Prophet.bannerAdMediationId);

			if (ProphetNative.IsTablet())
			{
				MaxAdvertHeight = com.google.android.gms.ads.AdSize.BANNER.getHeightInPixels(Prophet.appContext);
				this.bannerView.setAdSize(com.google.android.gms.ads.AdSize.BANNER);
			}
			else
			{
				MaxAdvertHeight = com.google.android.gms.ads.AdSize.BANNER.getHeightInPixels(Prophet.appContext);
				this.bannerView.setAdSize(com.google.android.gms.ads.AdSize.BANNER);
			}

			ProphetNative.SetMaxAdvertHeight(MaxAdvertHeight);
			if (Prophet.DEBUG) { Log.d(Prophet.TAG, String.format("ProphetAdvertising, Maximum advert height: %f", MaxAdvertHeight)); }

			//this.bannerView.setBackgroundColor(0x00000000);
				
			//	Sets up advert event listener
			this.bannerView.setAdListener(new com.google.android.gms.ads.AdListener() {

				@Override
				public void onAdLoaded()
				{
					if (Prophet.DEBUG) { Log.d(Prophet.TAG, "ProphetAdvertising, Banner advert loaded!"); }

					//	Disables retry timer
					Prophet.adverts.bannerRequestTimer = 0.f;

					super.onAdLoaded();
				}

				@Override
				public void onAdFailedToLoad(int errorCode)
				{
					if (Prophet.DEBUG) { Log.d(Prophet.TAG, "ProphetAdvertising, Banner advert failed to load!"); }

					//	Sets retry timer
					Prophet.adverts.bannerRequestTimer = gmBannerRequestDelay;
				}

				@Override
				public void onAdOpened()
				{
					super.onAdOpened();

					if (Prophet.DEBUG) { Log.d(Prophet.TAG, "ProphetAdvertising, Banner advert opened!"); }
				}

				@Override
				public void onAdLeftApplication()
				{
					if (Prophet.DEBUG) { Log.d(Prophet.TAG, "ProphetAdvertising, Banner advert left application!"); }
				}

				@Override
				public void onAdClosed()
				{
					super.onAdClosed();

					if (Prophet.DEBUG) { Log.d(Prophet.TAG, "ProphetAdvertising, Banner advert closed!"); }
				}
			});

			//	Sets up the banner layout
			this.bannerLayout = new RelativeLayout(Prophet.appActivity);
			this.bannerLayout.addView(this.bannerView);
			this.bannerLayout.setGravity(Prophet.bannerAdGravity);
			this.bannerLayout.bringToFront();

			params = new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);

			Prophet.appActivity.addContentView(this.bannerLayout, params);

			//	Request banner
			this.requestBanner();
		}
	}

The source code above is setup to use the BANNER advert size (320 x 50).  However we normally use the SMART_BANNER advert size.

With regards to SMART_BANNER implementation, we have also noticed that the MobFox 320 x 50 is justified towards the top of the AdMob banner space, any chance it could be centered vertically?  Below is a screen shot from an InMobi advert requested through the AdMob Mediation as a SMART_BANNER.  They have centered both horizontally and vertically in the AdMob banner space, which visually works well.

AdMob and Facebook SMART_BANNER

![admob-facebook](https://user-images.githubusercontent.com/28161411/28242205-6fa59484-699d-11e7-8f6f-c42254e2e914.png)

InMobi SMART_BANNER (InMobi do not support SMART_BANNER fully, so like MobFox they send an advert that will fit into the Ad Space).  In our tests we have received two sizes from InMobi, 320 x 50 and 468 x 60.

![inmobi2](https://user-images.githubusercontent.com/28161411/28242206-735d286c-699d-11e7-8f5e-11a1719910f5.png)

![inmobi1](https://user-images.githubusercontent.com/28161411/28242207-7505b38c-699d-11e7-97dc-4d2f46135a8c.png)

We fully understand that we will only get 320 x 50 banners from MobFox.  We just feel it would be visually more appealing if the black in-fill was removed and the advert centered vertically in the AdMob ad space as per InMobi.

Sorry to be a nuisance.

Regards,

iWare Designs.

**Comment by brachil** [comment]
Hi,
We fixed the regular banner so it should not act as smart banner.
And in the following link you can download a jar that supports a clear background frame for smart banner:
http://static.starbolt.io/MobFox-Android-AdMob-Adapter_transparent.jar
Please test and let us know if it worked,
Thanks.

**Comment by iWareDesigns** [comment]
Hi,
That does not appear to be working.
I have tried both banners and smart banners and I have not seen a single test advert for MobFox.
If I switch back to the previous adapter then I start seeing MobFox test adverts again.

When using the new adapter I am only seeing this line through Logcat with no test adverts:

`07-16 13:18:22.571 2906-2906/com.iwaredesigns.mybowling3d I/Ads: Instantiating mediation adapter: com.mobfox.adapter.MobFoxAdapter`

When using the older adapter I am getting all of this through Logcat and test adverts displayed:

```
07-16 13:23:35.868 9222-9222/com.iwaredesigns.mybowling3d I/Ads: Instantiating mediation adapter: com.mobfox.adapter.MobFoxAdapter
07-16 13:23:35.869 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: MobFox AdMob Adapter >> constructor
07-16 13:23:35.874 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: MobFox AdMob Adapter >> requestBannerAd 
07-16 13:23:35.874 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: MobFox AdMob Adapter >> init banner w:320 h:50
07-16 13:23:36.020 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxUtils: read setting
07-16 13:23:36.020 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: dmp post completed
07-16 13:23:36.024 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: Loading url http://sdk.starbolt.io/dist/tagBanner.html?v=3.2.7b_admob&s=fe96717d9875b9da4339ea5367eff1ec&sub_bundle_id=com.iwaredesigns.mybowling3d&adspace_height=50&adspace_width=320&c_mraid=1&dev_dnt=1&dev_js=1&rt=android_app
07-16 13:23:36.061 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxService: start service
07-16 13:23:38.442 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: MobFox AdMob Adapter >> Banner loaded
07-16 13:23:38.444 9222-9222/com.iwaredesigns.mybowling3d D/MobFoxBanner: MobFox AdMob Adapter >> getBannerView
```

Regards,

iWare Designs

**Comment by nabriski** [comment]
Puzzling, as we tested this adapter before sending it out. We'll try to reproduce this and understand the problem.

**Comment by iWareDesigns** [comment]
Hi,

I will keep it running at my end to see if any test adverts pop through.  You never know with Android, I am surprised anything works on it :)

Regards,

iWare Designs.

**Comment by brachil** [comment]
Please try:
http://static.starbolt.io/MobFox-Android-AdMob-Adapter-transparent2.jar

**Comment by iWareDesigns** [comment]
Hi,

Both BANNERS and SMART_BANNERS are working perfectly in the latest Adapter, thank you.

Should I use this adapter or will you be releasing a final version on GitHub?

Regards,

iWare Designs.

**Comment by brachil** [comment]
Ok cool, we updated the version in GitHub - so regular BANNER should work fine now.

But the feature you have for smart banner not having black in the side is only in your adapter for now, so if you want it use your jar :)

**Comment by iWareDesigns** [comment]
Hi,

Okay, thank you.  Hopefully in the future the smart banner not having black will find its way into your official release version.  After looking at InMobi and Facebook Audience Network they both do not adhere to AdMob's guidelines, they have opted for the more visually appealing option.

Again, thanks for all of your help.

Regards,

iWare Designs,
